"""Hub-changelog dispatch: detects when the running build's SHA differs
from the last one we sent to the changelog topic and emits a single
Telegram message listing the commits in between.

The "general / for-all" forum topic is reserved for this dispatch only —
all per-company alerts route to per-company topics via
`alerts.ensure_company_topic`. Topic auto-creates on first send via
`alerts.ensure_general_topic`.

Lifecycle:
  1. `build.py` writes `app/_version.py` with the current SHA + last 30
     commit subjects right before invoking PyInstaller.
  2. On hub start, `maybe_send_hub_changelog()` reads that stamp,
     compares to `cfg["telegram"]["last_changelog_sha"]`, and:
       - first run (no last_sha): silently saves baseline, no send.
       - SHA unchanged: noop.
       - SHA changed: builds an HTML message listing commits AFTER
         last_sha up to current, sends to the general topic, persists
         the new SHA.
  3. Operators can also force a re-send via the "Send hub changelog"
     button in the alerts panel (any company — it's not company-scoped).

When running from source there's no build step, so `_version.py` is
regenerated by `refresh_version_stamp()` (zero-arg, idempotent) before
the comparison. The function is a no-op when `git` is unavailable
(e.g. inside the bundled exe or a clean tarball install).
"""
from __future__ import annotations

import html
import subprocess
from pathlib import Path
from typing import Optional

try:
    from . import _version as version_mod  # type: ignore[no-redef]
except ImportError:
    # Fresh checkout / not yet stamped — runtime stub. The dev-mode
    # `_refresh_stamp_if_dev` will fill in real values when git is
    # available; otherwise the changelog hook silently no-ops.
    class _StubVersion:
        VERSION_SHA = ""
        VERSION_FULL_SHA = ""
        VERSION_SUBJECT = ""
        VERSION_BUILT_AT = ""
        RECENT_COMMITS: list[tuple[str, str]] = []
    version_mod = _StubVersion()  # type: ignore[assignment]

from .alerts import (
    GENERAL_TOPIC_NAME,
    get_last_changelog_sha,
    load_alerts_config,
    save_alerts_config,
    send_hub_changelog,
    set_last_changelog_sha,
)


# How many commits to bake into _version.py — generous for dev
# round-trips (operator might rebuild a few times before deploying).
RECENT_COMMITS_LIMIT = 30


# --- Stamp generation -------------------------------------------------------

def _git(args: list[str], cwd: Path) -> Optional[str]:
    try:
        out = subprocess.check_output(
            ["git", *args], cwd=str(cwd),
            stderr=subprocess.DEVNULL, timeout=10,
        )
        return out.decode("utf-8", "replace").strip()
    except (subprocess.CalledProcessError, FileNotFoundError, OSError, subprocess.TimeoutExpired):
        return None


def write_version_stamp(repo_root: Path) -> bool:
    """Write `app/_version.py` with the current HEAD SHA + last commits.
    Returns True on success, False when git isn't available / not a repo.
    Called from `build.py` before PyInstaller and (best-effort) from the
    runtime if `_version.py` is empty so dev runs also get a stamp.
    """
    head = _git(["rev-parse", "HEAD"], repo_root)
    if not head:
        return False
    short = _git(["rev-parse", "--short", head], repo_root) or head[:7]
    subject = _git(["log", "-1", "--pretty=%s", head], repo_root) or ""
    built_at = _git(["log", "-1", "--pretty=%cI", head], repo_root) or ""
    raw = _git(
        ["log", f"--max-count={RECENT_COMMITS_LIMIT}", "--pretty=%h%x09%s"],
        repo_root,
    ) or ""
    commits: list[tuple[str, str]] = []
    for line in raw.splitlines():
        if "\t" in line:
            sha, msg = line.split("\t", 1)
            commits.append((sha.strip(), msg.strip()))

    target = repo_root / "app" / "_version.py"
    body = (
        '"""Auto-generated by build.py / hub_changelog.write_version_stamp.\n'
        'Do not hand-edit — regenerated on every build."""\n\n'
        f'VERSION_SHA = {short!r}\n'
        f'VERSION_FULL_SHA = {head!r}\n'
        f'VERSION_SUBJECT = {subject!r}\n'
        f'VERSION_BUILT_AT = {built_at!r}\n'
        f'RECENT_COMMITS: list[tuple[str, str]] = {commits!r}\n'
    )
    try:
        target.write_text(body, encoding="utf-8")
    except OSError:
        return False
    return True


# --- Runtime dispatch -------------------------------------------------------

def _esc(s: str) -> str:
    return html.escape(str(s or ""), quote=False)


def _format_changelog_message(
    current_sha: str,
    current_subject: str,
    built_at: str,
    commits_since_last: list[tuple[str, str]],
) -> str:
    head_line = (
        f"🚀 <b>Aventus Bot Hub · build update</b>\n"
        f"📌 <code>{_esc(current_sha)}</code>"
    )
    if current_subject:
        head_line += f" — {_esc(current_subject)}"
    if built_at:
        head_line += f"\n🕒 <i>built {_esc(built_at)}</i>"

    if not commits_since_last:
        body = "<i>(no new commits between previous and current build)</i>"
    else:
        lines = []
        for sha, subj in commits_since_last:
            lines.append(f"• <code>{_esc(sha)}</code> — {_esc(subj)}")
        body = "<b>Commits since last build:</b>\n" + "\n".join(lines)

    return head_line + "\n\n" + body


def _refresh_stamp_if_dev() -> None:
    """If we appear to be running from source (cwd has a `.git` dir AND
    `_version.py` is empty/placeholder), regenerate the stamp so dev
    runs see meaningful changelogs. No-op when bundled or no git."""
    if version_mod.VERSION_SHA:
        return
    repo_root = Path(__file__).resolve().parents[1]
    if not (repo_root / ".git").exists():
        return
    write_version_stamp(repo_root)
    # Re-read the freshly-written constants. importlib.reload is fragile
    # in the middle of imports; instead re-exec the file.
    try:
        ns: dict = {}
        exec(
            (repo_root / "app" / "_version.py").read_text(encoding="utf-8"),
            ns,
        )
    except (OSError, SyntaxError):
        return
    for k in (
        "VERSION_SHA", "VERSION_FULL_SHA", "VERSION_SUBJECT",
        "VERSION_BUILT_AT", "RECENT_COMMITS",
    ):
        if k in ns:
            setattr(version_mod, k, ns[k])


def maybe_send_hub_changelog() -> Optional[str]:
    """Compare the build's stamped SHA to the last one we sent to the
    changelog topic. Send a message if changed; persist the new SHA.

    Returns:
      None — nothing to send (no stamp / first run / SHA unchanged /
             dispatch succeeded).
      str  — an error message when Telegram dispatch failed.

    Safe to call on every hub start. First run silently records the
    baseline so we don't spam on initial deploy.
    """
    _refresh_stamp_if_dev()
    if not version_mod.VERSION_SHA:
        return None  # No version stamp — running from a stripped checkout.

    cfg = load_alerts_config()
    last = get_last_changelog_sha(cfg)
    current = str(version_mod.VERSION_SHA)
    if not last:
        # First run after this feature shipped — don't blast the topic
        # with the historical changelog. Just record where we are.
        set_last_changelog_sha(cfg, current)
        try:
            save_alerts_config(cfg)
        except OSError:
            pass
        return None
    if last == current:
        return None

    # Slice RECENT_COMMITS at the last-seen SHA. The commit list is
    # newest-first, so we keep entries up to (but excluding) the last
    # SHA we already sent.
    commits_since: list[tuple[str, str]] = []
    for sha, subj in (version_mod.RECENT_COMMITS or []):
        if sha == last:
            break
        commits_since.append((sha, subj))

    text = _format_changelog_message(
        current_sha=current,
        current_subject=str(version_mod.VERSION_SUBJECT or ""),
        built_at=str(version_mod.VERSION_BUILT_AT or ""),
        commits_since_last=commits_since,
    )
    err = send_hub_changelog(cfg, text)
    if err is None:
        set_last_changelog_sha(cfg, current)
        try:
            save_alerts_config(cfg)
        except OSError:
            pass
    return err


__all__ = [
    "GENERAL_TOPIC_NAME",
    "maybe_send_hub_changelog",
    "write_version_stamp",
]
